#ifndef GV_ABC_CMD_H
#define GV_ABC_CMD_H

#include "gvCmdMgr.h"

GV_COMMAND(GVABCReadCmd, GV_CMD_TYPE_ABC);
GV_COMMAND(GVABCPrintCmd, GV_CMD_TYPE_ABC);
GV_COMMAND(GVABCNtk2AigCmd, GV_CMD_TYPE_ABC);
GV_COMMAND(GVABCSweepCmd, GV_CMD_TYPE_ABC);
GV_COMMAND(GVAIGFraigCmd, GV_CMD_TYPE_ABC);
GV_COMMAND(GVAIGPrintCmd, GV_CMD_TYPE_ABC);
GV_COMMAND(GVAIGRAndomSimCmd, GV_CMD_TYPE_ABC);
GV_COMMAND(GVABCOriginalCmd, GV_CMD_TYPE_ABC);
GV_COMMAND(GVCutEnumerate, GV_CMD_TYPE_ABC);
GV_COMMAND(GVSimilarityCompute, GV_CMD_TYPE_ABC);

#endif