# abc
git clone https://github.com/berkeley-abc/abc
cd abc
make -j8
cd ../

# yosys
git clone https://github.com/YosysHQ/yosys.git
cd yosys;
sudo apt-get install build-essential clang bison flex \
	libreadline-dev gawk tcl-dev libffi-dev git \
	graphviz xdot pkg-config python3 libboost-system-dev \
	libboost-python-dev libboost-filesystem-dev zlib1g-dev;
make config-clang; make -j8;
sudo make install;

# clear
clear